### ISSUE TITLE
text file doesn't open by clicking

### ISSUE THREAD

**Issue by iamgr007** [othmanalbahri1/prioritymatrix#1]
Clicking on Do now, Delegate, Schedule, or Eliminate opens a text file to enter/edit tasks doesn't open the text file! Does it have anything to do with my PC settings? please check.

**Comment by othmanalbahri1** [comment]
Hi @iamgr007, 

I haven't been able to reproduce this on my machines. I suspect that it has something to do with your machine. 

What is your default text editor? Can you open .txt files by double-clicking on them?

Here's a portable Rainmeter version with PriorityMatrixi included, which works on my machine. Could you please try it and let me know how it goes? You simply have to unzip the file and run Rainmeter.exe; it should load PriorityMatrix for you automatically.

[Rainmeter.zip](https://github.com/othmanalbahri1/prioritymatrix/files/5792858/Rainmeter.zip)

**Comment by iamgr007** [comment]
Yeah thanks! This Rainmeter version worked just fine. Maybe the problem is in the current rainmeter version, you might as well check it on some device and update rainmeter about this issue!
Thanks mate! Great work btw, I loved it and shared with my pals and they are in awe! 💯 :)

**Comment by othmanalbahri1** [comment]
Excellent! Glad it's worked for you. I'll add this file to the instructions page in case others have similar issues.

Thanks a lot! Hope it helps :)
